export const CONSULTATION_URL = 'https://cal.com/redsquirrel/30min'
export const INSTAGRAM_URL = 'https://www.instagram.com/redsquirrel_a/'
export const TELEGRAM_URL = 'https://t.me/alenadomozhirova'
export const WHATSAPP_URL = 'https://wa.me/+4915209064235'
export const FACEBOOK_URL = 'https://www.facebook.com/domozhirovaalena'
export const EMAIL_URL = 'mailto:info@redsquirrel.agency'
