<template>
  <div
    ref="containerRef"
    class="container"
    :class="mdAndUp ? 'desktop' : 'mobile'"
  >
    <div class="offer text-center">
      <FacebookRating class="facebook-rating" />
      <h2>
        <HeadingText
          :text="$t('We are chosen for our high level of expertise and service')"
          :line-breaks="mdAndUp ? [4, 8] : [2, 6, 9]"
          :font-replacements="[[0, 0], [2, 2], [6, 2], [8, 3], [10, 0]]"
        />
      </h2>
      <p class="ai-note">
        {{ $t('Photos and voices are generated by AI due to the confidentiality of our clients') }}
      </p>
    </div>
    <div class="review-cards">
      <GlassSheet
        v-for="(review, index) in reviews"
        :key="index"
        :style="mdAndUp && { ...review.position }"
        :elevation="isReviewCardElevated(index) ? 24 : 8"
        :class="isReviewCardElevated(index) && 'elevated'"
        :border="mdAndUp ? '1vw' : '7.81vw'"
        class="review-card"
        @click="onReviewClick(review, index)"
        @mouseover="hovered = index"
        @mouseleave="hovered = -1"
      >
        <div
          class="avatar-wrapper"
          :class="(selected === index && playing) && 'pulsate'"
        >
          <v-avatar class="avatar">
            <v-img
              :alt="review.company"
              :src="getAvatarUrlById(review.id)"
              eager
            />
          </v-avatar>
        </div>
        <div>
          <div class="company">
            {{ review.company }}
          </div>
          <div class="niche">
            {{ $t(review.niche) }}
          </div>
        </div>
        <div
          v-if="!mdAndUp"
          class="play-pause-icon"
        >
          <PauseCircleFilledIcon
            v-if="isReviewCardPlaying(index)"
            color="#FFE6DA"
          />
          <PlayCircleFilledIcon
            v-else
            color="#FFE6DA"
          />
        </div>
      </GlassSheet>
    </div>
    <v-snackbar
      v-model="snackbar"
      :timeout="10000"
      :text="$t('Click on the card to play the review')"
      :width="mdAndUp ? '600px' : undefined"
      timer="#C38D72"
      color="rgba(255, 255, 255, 0.5)"
      rounded="lg"
      height="63px"
    />
    <Transition>
      <AudioPlayer
        v-if="sound"
        v-model="playing"
        :sound="sound"
        class="player"
        @close="onAudioPlayerClose()"
      />
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { useDisplay } from 'vuetify'

const { mdAndUp } = useDisplay()
const { locale } = useI18n()

interface IReviewPosition {
  top?: string
  bottom?: string
  left?: string
  right?: string
}

interface IReview {
  id: string
  company: string
  niche: string
  position: IReviewPosition
}

const sound = ref<ISound>()
const hovered = ref<number>(-1)
const selected = ref<number>(-1)
const playing = ref(false)
const snackbar = ref(false)

function onReviewClick(review: IReview, index: number) {
  if (selected.value === index) {
    playing.value = !playing.value
    return
  }
  selected.value = index
  sound.value = {
    name: review.company,
    src: getAudioUrlById(review.id),
    subtitlesSrc: getSubtitlesUrlById(review.id)
  }
  snackbar.value = false
}

function onAudioPlayerClose() {
  selected.value = -1
  sound.value = undefined
  playing.value = false
}

function isReviewCardPlaying(index: number) {
  return selected.value === index && playing.value
}

function isReviewCardElevated(index: number) {
  if (!mdAndUp.value) return false
  return isReviewCardPlaying(index) || hovered.value === index
}

function getAvatarUrlById(id: string): string {
  return `reviews/avatars/${id}.png`
}

function getAudioUrlById(id: string): string {
  return `reviews/audio/${id}_${locale.value}.mp3`
}

function getSubtitlesUrlById(id: string): string {
  return `reviews/subtitles/${id}_${locale.value}.srt`
}

function toggleSnackbar(display: boolean) {
  snackbar.value = display
}

function onContainerEnter() {
  if (selected.value != -1) return
  toggleSnackbar(true)
}

function onContainerLeave() {
  onAudioPlayerClose()
  toggleSnackbar(false)
}

const containerRef = ref()
const { $gsap } = useNuxtApp()
onMounted(() => {
  const container = containerRef.value

  const offerItems = container.querySelectorAll('.offer > *')
  const reviewCards = container.querySelectorAll('.review-card')

  const offerItemsArray = $gsap.utils.toArray(offerItems) as HTMLElement[]
  const reviewCardsArray = $gsap.utils.toArray(reviewCards) as HTMLElement[]

  $gsap.to(container, {
    scrollTrigger: {
      trigger: container,
      start: 'top center',
      end: 'bottom bottom',
      scrub: true
    },
    onStart: onContainerEnter,
    onComplete: onContainerLeave,
    onReverseComplete: onContainerLeave
  })

  for (const reviewCard of reviewCardsArray) {
    $gsap.effects.slideBottom(reviewCard, {
      duration: 0.5,
      scrollTrigger: {
        trigger: reviewCard,
        start: 'bottom bottom',
        toggleActions: 'play none resume reverse'
      }
    })
  }

  for (const offerItem of offerItemsArray) {
    $gsap.effects.slideTop(offerItem, {
      duration: 0.5,
      scrollTrigger: {
        trigger: offerItem,
        start: 'bottom bottom',
        toggleActions: 'play none resume reverse'
      }
    })
  }
})

const reviews: IReview[] = [
  {
    id: 'oom_store',
    company: 'OOM Store',
    niche: 'Handmade Wrap Pants',
    position: { top: '10.4vw', left: '33.8vw' }
  },
  {
    id: 'landystyle',
    company: 'LandyStyle',
    niche: 'Landscape Agency',
    position: { top: '6.9vw', left: '52.8vw' }
  },
  {
    id: 'natalie_herzel',
    company: 'Natalie Herzel',
    niche: 'Dental Clinic',
    position: { top: '8.3vw', left: '14.9vw' }
  },
  {
    id: 'ambre_akadeemia',
    company: 'Ambre Akadeemia',
    niche: 'Language School',
    position: { top: '12.5vw', left: '71.8vw' }
  },
  {
    id: 'dreamlis',
    company: 'Dreamlis',
    niche: 'Jewelry Brand',
    position: { top: '28vw', left: '8.3vw' }
  },
  {
    id: 'integrator_digital',
    company: 'Integrator Digital',
    niche: 'CRM Systems for Business',
    position: { top: '32.2vw', left: '78.4vw' }
  },
  {
    id: 'marketing_etico',
    company: 'Marketing Etico',
    niche: 'Marketing Agency',
    position: { top: '47.8vw', left: '14.9vw' }
  },
  {
    id: 'ezdesign',
    company: 'EZdesign',
    niche: 'Bureau of Architecture',
    position: { top: '50.5vw', left: '71.8vw' }
  },
  {
    id: 'nuga_best_eesti',
    company: 'Nuga Best Eesti',
    niche: 'Medical Equipment',
    position: { top: '56.9vw', left: '33.8vw' }
  },
  {
    id: 'laruhelpsukraine',
    company: 'LaruHelpsUkraine',
    niche: 'Charity Organization',
    position: { top: '54.8vw', left: '52.8vw' }
  }
]
</script>

<style scoped lang="scss">
@import "styles/variables";

.container {
  color: $redsquirrel-cream;
}

.facebook-rating {
  color: $redsquirrel-cream;
}

.desktop {
  display: flex;
  justify-content: center;
  position: relative;
  height: 78vw;

  .offer {
    position: absolute;
    top: 27.6vw;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  h2 {
    font-size: 3vw;
    line-height: 4.5vw;
    margin: 1vw 0;
  }

  .ai-note {
    width: 25vw;
    font-size: 1.3vw;
    line-height: 2vw;
  }

  .review-card {
    position: absolute;
    width: 13vw;
    padding: 0.8vw 1.3vw 1.3vw;
    cursor: pointer;

    display: flex;
    align-items: center;
    flex-direction: column;

    &.elevated {
      scale: 1.05 !important;
    }

    .avatar-wrapper {
      height: 8vw;
      width: 8vw;
      display: flex;
      justify-content: center;
      margin-bottom: 0.95vw;

      .avatar {
        height: 7vw;
        width: 7vw;
        outline: 1px solid rgba(255, 255, 255, 1);
        margin: auto 0;
      }

      &.pulsate {
        animation: pulsate-desktop 1s linear infinite alternate;
      }
    }

    .company {
      font-size: 1.02vw;
      line-height: 1.9vw;
      text-align: center;
    }

    .niche {
      font-size: 1.05vw;
      line-height: 1vw;
      text-align: center;
    }
  }
}

.mobile {
  height: 100vh;
  font-size: 3.75vw;
  line-height: 5.625vw;
  padding: 3.125vw;

  h2 {
    font-size: 9.375vw;
    line-height: 12.656vw;
    margin: 6.25vw 0;
  }

  .review-cards {
    display: flex;
    flex-direction: column;
    flex-wrap: wrap;
    justify-content: center;
    gap: 1.56vw;
    margin-top: 15.625vw;
  }

  .review-card {
    padding: 2vw 4.68vw 2vw 1vw;
    display: flex;
    align-items: center;

    .avatar-wrapper {
      height: 14vw;
      width: 14vw;
      display: flex;
      justify-content: center;
      margin-right: 3.125vw;

      .avatar {
        height: 12.5vw;
        width: 12.5vw;
        outline: 1px solid rgba(255, 255, 255, 1);
        margin: auto 0;
      }

      &.pulsate {
        animation: pulsate-mobile 1s linear infinite alternate;
      }
    }

    .niche {
      font-size: 3.125vw;
      line-height: 3.125vw;
    }

    .play-pause-icon {
      display: flex;
      align-items: center;
      margin-left: auto;

      svg {
        width: 10.625vw;
        height: 10.625vw;
      }
    }
  }
}

h2 {
  font-weight: 400;
  text-transform: uppercase;
}

.ai-note {
  font-weight: 400;
  text-transform: uppercase;
}

.review-card {
  transition: box-shadow 0.3s ease-in-out, scale 0.3s ease-in-out;

  .avatar-wrapper {
    border-radius: 100%;

    .avatar {
      outline: 1px solid rgba(255, 255, 255, 1);
      margin: auto 0;
    }

    &.pulsate {
      .avatar {
        outline: 0;
      }
      animation: pulsate-desktop 1s linear infinite alternate;
    }
  }

  .company {
    text-transform: uppercase;
    font-weight: 400;
    color: $redsquirrel-cream-m1;
  }

  .niche {
    font-weight: 400;
    color: $redsquirrel-cream;
  }
}

@keyframes pulsate-desktop {
  0% {
    background: rgba($redsquirrel-cream-m1, 0);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0);
  }
  50% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0);
  }
  100% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0.2);
  }
}

@keyframes pulsate-mobile {
  0% {
    background: rgba($redsquirrel-cream-m1, 0);
    outline: 0.8vw solid rgba($redsquirrel-cream-m1, 0);
  }
  50% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.8vw solid rgba($redsquirrel-cream-m1, 0);
  }
  100% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.8vw solid rgba($redsquirrel-cream-m1, 0.2);
  }
}

.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
