<template>
  <div
    ref="containerRef"
    class="container d-flex justify-center"
  >
    <div class="offer text-center">
      <FacebookRating class="facebook-rating" />
      <h2>
        <HeadingText
          :text="$t('We are chosen for our high level of expertise and service')"
          :line-breaks="[4, 8]"
          :font-replacements="[[0, 0], [2, 2], [6, 2], [8, 3], [10, 0]]"
        />
      </h2>
      <p class="ai-note">
        <HeadingText
          :text="$t('Photos and voices are generated by AI due to the confidentiality of our clients')"
          :line-breaks="[4, 11]"
        />
      </p>
    </div>
    <GlassSheet
      v-for="(review, index) in reviews"
      ref="reviewCardsRef"
      :key="index"
      :style="{ position: 'absolute', ...review.position }"
      :elevation="isReviewCardElevated(index) ? 24 : 8"
      border="1vw"
      class="review-card"
      :class="isReviewCardElevated(index) && 'closer'"
      @click="onReviewClick(review, index)"
      @mouseover="hovered = index"
      @mouseleave="hovered = -1"
    >
      <div
        class="d-flex justify-center align-center"
        style="flex-direction: column"
      >
        <div
          class="avatar-wrapper"
          :class="(selected === index && playing) && 'pulsate'"
        >
          <v-avatar class="avatar">
            <v-img
              :alt="review.company"
              :src="review.avatar"
              eager
            />
          </v-avatar>
        </div>
        <div class="company text-center">
          {{ review.company }}
        </div>
        <div class="niche text-center">
          {{ $t(review.niche) }}
        </div>
      </div>
    </GlassSheet>
    <Transition>
      <AudioPlayer
        v-if="sound"
        class="player"
        :sound="sound"
        @play="playing = true"
        @end="playing = false"
        @stop="playing = false"
        @pause="playing = false"
        @close="onAudioPlayerClose()"
      />
    </Transition>
    <v-snackbar
      v-model="snackbar"
      :timeout="10000"
      :text="$t('Click on the card to play the review')"
      timer="#C38D72"
      color="rgba(255, 255, 255, 0.5)"
      rounded="lg"
      width="600px"
      height="63px"
    />
  </div>
</template>

<script setup lang="ts">
interface IReviewPosition {
  top?: string
  bottom?: string
  left?: string
  right?: string
}

interface IReview {
  company: string
  niche: string
  avatar: string
  sound: ISound
  position: IReviewPosition
}

const sound = ref<ISound>()
const hovered = ref<number>(-1)
const selected = ref<number>(-1)
const playing = ref(false)
const snackbar = ref(false)

function onReviewClick(review: IReview, index: number) {
  selected.value = index
  sound.value = { name: review.company, ...review.sound }
  snackbar.value = false
}

function onAudioPlayerClose() {
  selected.value = -1
  sound.value = undefined
  playing.value = false
}

function isReviewCardElevated(index: number) {
  return ((selected.value === index && playing.value) || (hovered.value === index))
}

function toggleSnackbar(display: boolean) {
  snackbar.value = display
}

const containerRef = ref()
function onDocumentScroll() {
  const container = containerRef.value
  const topOffset = container.offsetTop - window.scrollY
  const offsetHeight = container.offsetHeight
  if ((topOffset + offsetHeight * -0.7) > 0 || (topOffset + offsetHeight * 0.5) < 0) {
    onAudioPlayerClose()
    toggleSnackbar(false)
  }
}
document.addEventListener('wheel', onDocumentScroll, { passive: false })

const { $gsap } = useNuxtApp()
onMounted(() => {
  const container = containerRef.value
  const offer = container.querySelector('.offer')
  const reviewCards = container.querySelectorAll('.review-card')
  const reviewCardsArray = $gsap.utils.toArray(reviewCards) as HTMLElement[]

  for (const reviewCard of reviewCardsArray) {
    $gsap.effects.slideBottom(reviewCard, {
      duration: 0.5,
      scrollTrigger: {
        trigger: reviewCard,
        start: 'top center',
        toggleActions: 'play none resume reverse'
      }
    })
  }

  $gsap.effects.slideTop(offer, {
    duration: 0.8,
    scrollTrigger: {
      trigger: offer,
      start: 'top center',
      toggleActions: 'play none resume reverse'
    },
    onComplete: () => toggleSnackbar(true)
  })
})

const reviews: IReview[] = [
  {
    company: 'OOM Store',
    niche: 'Handmade Wrap Pants',
    avatar: 'avatars/oom_store.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '10.4vw', left: '33.8vw' }
  },
  {
    company: 'LandyStyle',
    niche: 'Landscape Agency',
    avatar: 'avatars/landystyle.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '6.9vw', left: '52.8vw' }
  },
  {
    company: 'Natalie Herzel',
    niche: 'Dental Clinic',
    avatar: 'avatars/natalie_herzel.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '8.3vw', left: '14.9vw' }
  },
  {
    company: 'Ambre Akadeemia',
    niche: 'Language School',
    avatar: 'avatars/ambre_akadeemia.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '12.5vw', left: '71.8vw' }
  },
  {
    company: 'Dreamlis',
    niche: 'Jewelry Brand',
    avatar: 'avatars/dreamlis.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '28vw', left: '8.3vw' }
  },
  {
    company: 'Integrator Digital',
    niche: 'CRM Systems for Business',
    avatar: 'avatars/integrator_digital.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '32.2vw', left: '78.4vw' }
  },
  {
    company: 'Marketing Etico',
    niche: 'Marketing Agency',
    avatar: 'avatars/marketing_etico.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '47.8vw', left: '14.9vw' }
  },
  {
    company: 'EZdesign',
    niche: 'Bureau of Architecture',
    avatar: 'avatars/ezdesign.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '50.5vw', left: '71.8vw' }
  },
  {
    company: 'Nuga Best Eesti',
    niche: 'Medical Equipment',
    avatar: 'avatars/nuga_best_eesti.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '56.9vw', left: '33.8vw' }
  },
  {
    company: 'LaruHelpsUkraine',
    niche: 'Charity Organization',
    avatar: 'avatars/laruhelpsukraine.png',
    sound: { src: 'audio/landystyle_en.mp3', subtitlesSrc: 'subtitles/landystyle_en.srt' },
    position: { top: '54.8vw', left: '52.8vw' }
  }
]
</script>

<style scoped lang="scss">
@import "styles/variables";

.container {
  position: relative;
  height: 78vw;
}

.offer {
  position: absolute;
  top: 27.6vw;
  display: flex;
  flex-direction: column;
  justify-content: center;

  .facebook-rating {
    color: $redsquirrel-cream;
  }

  h2 {
    font-size: 3vw;
    font-weight: 400;
    line-height: 4.5vw;
    text-transform: uppercase;
    color: $redsquirrel-cream;
    margin: 1vw 0;
  }

  .ai-note {
    font-size: 1.3vw;
    font-weight: 400;
    line-height: 2vw;
    text-transform: uppercase;
    color: $redsquirrel-cream;
  }
}

.review-card {
  width: 13vw;
  padding: 0.8vw 1.3vw 1.3vw;
  border: 1px solid rgba(255, 255, 255, 0.7);
  transition: box-shadow 0.3s ease-in-out, scale 0.3s ease-in-out;
  cursor: pointer;

  &.closer {
    scale: 1.05;
  }

  .avatar-wrapper {
    height: 8vw;
    width: 8vw;
    display: flex;
    justify-content: center;
    border-radius: 100%;
    margin-bottom: 0.95vw;

    .avatar {
      height: 7vw;
      width: 7vw;
      outline: 1px solid rgba(255, 255, 255, 0.7);
      margin: auto 0;
    }

    &.pulsate {
      .avatar {
        outline: 0;
      }
      animation: pulsate 1s linear infinite alternate;
    }
  }

  .company {
    text-transform: uppercase;
    font-size: 1.02vw;
    line-height: 1.9vw;
    font-weight: 400;
    color: $redsquirrel-cream-m1;
  }

  .niche {
    font-size: 1.05vw;
    line-height: 1vw;
    color: $redsquirrel-cream-p1;
  }
}

.snackbar {
  position: fixed;
  z-index: 5;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  bottom: 20px;
  width: 600px;
  padding: 20px;
}

.player {
  position: fixed;
  z-index: 5;
  margin-left: auto;
  margin-right: auto;
  left: 0;
  right: 0;
  bottom: 20px;
  width: 600px;
}

@keyframes pulsate {
  0% {
    background: rgba($redsquirrel-cream-m1, 0);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0);
  }
  50% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0);
  }
  100% {
    background: rgba($redsquirrel-cream-m1, 0.5);
    outline: 0.5vw solid rgba($redsquirrel-cream-m1, 0.2);
  }
}

.v-enter-active,
.v-leave-active {
  transition: opacity 0.5s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>
